# Enviroment variable check
ifeq ($(wildcard $(NEMU_HOME)/src/nemu-main.c),)
  $(error NEMU_HOME=$(NEMU_HOME) is not a NEMU repo)
endif
ifeq ($(wildcard $(DIFF_HOME)/csrc/diff-main.cpp),)
  $(error DIFF_HOME=$(DIFF_HOME) is not a DIFFTEST repo)
endif

# Include variables and rules generated by menuconfig
-include $(DIFF_HOME)/include/config/auto.conf
-include $(DIFF_HOME)/include/config/auto.conf.cmd

TOPNAME = mycpu_top
VSRC_DIR = $(DIFF_HOME)/vsrc
VSRC_SUB_DIR = $(shell find -L $(VSRC_DIR)/ -type d)
VINCLUDE = $(addprefix -I, $(VSRC_SUB_DIR))
VLOG_DIR = $(DIFF_HOME)/vlogs
MAINNAME = mysim_main
# verilator -Mdir Name of output object directory
VXX_MDIR = $(DIFF_HOME)/obj_dir
CSRC_DIR = $(DIFF_HOME)/csrc
VXX_WNO = -Wno-caseincomplete \
		  -Wno-width \
		  -Wno-pinmissing \
		  -Wno-implicit \
		  -Wno-timescalemod
CFLAGS = -I$(DIFF_HOME)/include -g
CFLAGS += -DNSCSCC_HOME=\\\"$(NSCSCC_HOME)\\\"
CFLAGS += -DDIFF_HOME=\\\"$(DIFF_HOME)\\\"
NPROC = $(shell nproc)

VXXFLAG = --cc -D__SIM_IP__ --Mdir $(VXX_MDIR) $(VXX_WNO) -LDFLAGS "-lpthread" --relative-includes $(VINCLUDE) -CFLAGS "$(CFLAGS)" -j $(NPROC)
ifdef CONFIG_TRACE_ON
	VXXFLAG += --trace$(if $(CONFIG_EXT_FST),-fst)
endif

VXXBIN = V$(TOPNAME)
VSRC_TOP = $(VSRC_DIR)/$(TOPNAME).v
VSRC_ALL = $(shell find $(VSRC_DIR) -type f -name "*.v")
CSRC = $(shell find $(CSRC_DIR) -type f -name "*.cpp")

.PHONY: clean head sim wave var

var:

include $(DIFF_HOME)/scripts/config.mk

head: $(VSRC_ALL)
	verilator $(VXXFLAG) $(VSRC_TOP) 

$(VXXBIN): $(VSRC_ALL) $(CSRC)
	verilator $(VXXFLAG) --exe $(VSRC_TOP) $(CSRC) --build
 
sim: $(VXXBIN)
	$(VXX_MDIR)/V$(TOPNAME)

wave:
	gtkwave ./*.vcd signals.sav -S marker.tcl

clean:
ifndef VSRC_DIR
	@echo Please first DEFINE variable "VXX_MDIR"
else
	rm -rf $(VXX_MDIR)/*
endif
