# Enviroment variable check
ifeq ($(wildcard $(NEMU_HOME)/src/nemu-main.c),)
  $(error NEMU_HOME=$(NEMU_HOME) is not a NEMU repo)
endif
ifeq ($(wildcard $(DIFF_HOME)/csrc/diff-main.cpp),)
  $(error DIFF_HOME=$(DIFF_HOME) is not a DIFFTEST repo)
endif

# Include variables and rules generated by menuconfig
-include $(DIFF_HOME)/include/config/auto.conf
-include $(DIFF_HOME)/include/config/auto.conf.cmd

TOPNAME = mycpu_top
VSRC_DIR = $(DIFF_HOME)/vsrc
VSRC_SUB_DIR = $(shell find -L $(VSRC_DIR)/ -type d)
VINCLUDE = $(addprefix -I, $(VSRC_SUB_DIR))
VLOG_DIR = $(DIFF_HOME)/vlogs
MAINNAME = mysim_main
# verilator -Mdir Name of output object directory
VXX_MDIR = $(DIFF_HOME)/obj_dir
CSRC_DIR = $(DIFF_HOME)/csrc
VXX_WNO = -Wno-caseincomplete \
		  -Wno-width \
		  -Wno-pinmissing \
		  -Wno-implicit \
		  -Wno-timescalemod
CFLAGS = -I$(DIFF_HOME)/include
CFLAGS += -I$(NEMU_HOME)/include
CFLAGS += -DNSCSCC_HOME=\\\"$(NSCSCC_HOME)\\\"
CFLAGS += -DDIFF_HOME=\\\"$(DIFF_HOME)\\\"
CFLAGS += -D__DIFF_PROJ__=1
CFLAGS += -g
NPROC = $(shell nproc)

VXXFLAG = --cc -D__SIM_IP__ --Mdir $(VXX_MDIR) $(VXX_WNO) --relative-includes $(VINCLUDE) -CFLAGS "$(CFLAGS)" 
VXXFLAG += -j $(NPROC)
ifdef CONFIG_TRACE_ON
	VXXFLAG += --trace$(if $(CONFIG_EXT_FST),-fst)
endif

VXXBIN = $(VXX_MDIR)/V$(TOPNAME)
VSRC_TOP = $(VSRC_DIR)/$(TOPNAME).v
VSRC_ALL = $(shell find $(VSRC_DIR) -type f -name "*.v")
CSRC = $(shell find $(CSRC_DIR) -type f -name "*.cpp")

.PHONY: clean head sim wave var


Kconfig := $(DIFF_HOME)/Kconfig
include $(NEMU_HOME)/scripts/config.mk

ARGS := -l $(VLOG_DIR)/log.txt -d $(NEMU_HOME)/build/mips32-nemu-interpreter-so

var:

head: $(VSRC_ALL)
	verilator $(VXXFLAG) $(VSRC_TOP) 

$(VXXBIN): $(VSRC_ALL) $(CSRC)
	verilator $(VXXFLAG) --exe $(VSRC_TOP) $(CSRC) --build
 
sim: $(VXXBIN)
	$(VXXBIN) $(ARGS)

gdb: $(VXXBIN)
	gdb -s $(VXXBIN) --args $(VXXBIN) $(ARGS)

wave:
	gtkwave vlogs/wave/*.fst vlogs/wave/signals.sav

clean:
ifndef VSRC_DIR
	@echo Please first DEFINE variable "VXX_MDIR"
else
	rm -rf $(VXX_MDIR)/*
endif
